{{- if .Values.role.tfState.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "argo-workflows-execution.roleKind" . }}
metadata:
  name: {{ include "argo-workflows-execution.roleK8SStateName" . }}
  {{- if eq .Values.role.type "Role" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "argo-workflows-execution.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: [ "list","get","watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"] # "" indicates the core API group
  resources: ["leases"]
  verbs: ["get","create", "update", "patch", "delete"]
{{- end }}
