{{- if .Values.roleBinding.vaultInjector.create }}
kind: {{ include "argo-workflows-execution.roleBindingKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "argo-workflows-execution.roleVaultInjectorName" . }}
  {{- if eq .Values.roleBinding.type "Role" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "argo-workflows-execution.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "argo-workflows-execution.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  {{- if eq .Values.role.type "ClusterRole" }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "argo-workflows-execution.roleVaultInjectorName" . }}
  apiGroup: ""
{{- end }}