{{- if .Values.role.vaultInjector.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "argo-workflows-execution.roleKind" . }}
metadata:
  name: {{ include "argo-workflows-execution.roleVaultInjectorName" . }}
  {{- if eq .Values.role.type "Role" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "argo-workflows-execution.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - patch 
  - get
  - watch
{{- end }}
