apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: app-cert-manager-webhook-duckdns
spec:
  entrypoint: exec
  templates:
    - inputs:
        parameters:
          - name: name-prefix
            default: ""
          - name: issuerEmail
          - name: destination-name
            default: in-cluster
          - name: externalsecrets-enabled
            default: "false"
      name: exec
      resource:
        action: apply
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: {{inputs.parameters.name-prefix}}cert-manager-webhook-duckdns
          spec:
            destination:
              name: {{inputs.parameters.destination-name}}
              namespace: cert-manager
            project: default
            # hack for ignore changed duration format from 43800h to 43800h0m0s
            ignoreDifferences:
            - group: cert-manager.io
              kind: Certificate
              jsonPointers:
              - /spec/duration
            source:
              chart: cert-manager-webhook-duckdns
              repoURL: https://nolte.github.io/helm-charts-repo
              targetRevision: 0.2.2
              #path: src/applications/cert-manager-webhook-duckdns/deploy/chart
              #repoURL: https://github.com/nolte/argo-charts.git
              #targetRevision: master
              helm:
                releaseName: cert-manager-webhook-duckdns
                parameters:
                  - name: certmanagerwebhookduckdns.fullnameOverride
                    value: "cert-manager-webhook-duckdns"
                  - name: certmanagerwebhookduckdns.clusterIssuer.email
                    value: "{{inputs.parameters.issuerEmail}}"
                  - name: certmanagerwebhookduckdns.clusterIssuer.production.create
                    value: "true"
                  - name: certmanagerwebhookduckdns.clusterIssuer.staging.create
                    value: "true"                 
                  - name: certmanagerwebhookduckdns.secret.existingSecret
                    value: "true"
                  - name: certmanagerwebhookduckdns.secret.existingSecretName
                    value: "duckdns-token"
                  - name: externalsecrets.enabled
                    value: "{{inputs.parameters.externalsecrets-enabled}}"