apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.spec | nindent 2}}