apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - behavior: merge
    literals:
      - state.5.path="./src/clusters/dev-kind-powerdns"
    name: screenplay-bootstrap

resources:
  - ../base
  - ../applications
