apiVersion: kustomize.config.k8s.io/v1beta1
# commonLabels:
#   argocd.argoproj.io/instance: seed-job
kind: Kustomization
namespace: argocd

generatorOptions:
 disableNameSuffixHash: true


patches:
  - path: deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1

resources:
  - ../../../src/applications/metallb/deploy/argocd
  - ../../../src/applications/ingress-nginx/deploy/argocd
  - ../../../src/applications/stakater-reloader/deploy/argocd
  - ../../../src/applications/reflector/deploy/argocd
  - ../../../src/applications/cert-manager/deploy/argocd
  #- ../../../src/applications/cert-manager-webhook-duckdns/deploy/argocd

