apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
spec:
  destination:
    name: in-cluster
    namespace: operators
  project: default
  source:
    path: src/applications/knative/deploy/kustomize/operator
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master