apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: admin-user
spec:
  tags:
  - management # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
  - policymaker
  - administrator
  rabbitmqClusterReference:
    name: transport
  importCredentialsSecret:
    name: admin-user-credentials-secret
