apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  #annotations:
  #  argocd.argoproj.io/sync-wave: "15"
spec:
  destination:
    name: in-cluster
    namespace: external-dns
  project: default
  sources:
    - chart: external-secrets-manifests
      repoURL: https://nolte.github.io/helm-charts-repo/
      targetRevision: 1.1.0
      helm:
        releaseName: external-secrets-manifests
        valuesObject:
          secretstore:
            create: false
            serviceAccount:
              create: false
          secrets:
            pdns-access:
              data:
                - key: services/dns/users/root
                  name: pdns_api_key
                  property: token

    - # https://artifacthub.io/packages/helm/bitnami/external-dns
      chart: external-dns
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 8.8.3
      helm:
        releaseName: external-dns
        valuesObject:
          global:
            security:
              allowInsecureImages: true
          # image:
          #   registry: gcr.io
          #   repository: k8s-staging-external-dns/external-dns
          #   #tag: 0.16.1-debian-12-r5
          #   digest: "sha256:6bc072a532e1e29c02b45298a4570b8af6a353e82373dacc4a9b8cf6855e0201"
          #   # /@sha256:6bc072a532e1e29c02b45298a4570b8af6a353e82373dacc4a9b8cf6855e0201 
          pdns:
            apiUrl: http://powerdns.powerdns.svc
            secretName: pdns-access

          provider: pdns
          txtOwnerId: "play-external-dns"
          domainFilters:
            - "dev44-just-homestyle.duckdns.org"
            - "smart-home.k8sservices.local"
          sources:
            - contour-httpproxy
            - ingress
            - service
