apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  #annotations:
  #  argocd.argoproj.io/sync-wave: "15"
spec:
  destination:
    name: in-cluster
    namespace: external-dns
  project: default
  source:
    chart: external-dns
    repoURL: https://nolte.github.io/helm-charts-repo
    targetRevision: 0.0.2
    helm:
      releaseName: external-dns
      parameters:
        - name: externalSecret.create
          value: "true"
      values: |
        externaldns:
           sources:
             - contour-httpproxy
             - contour-ingressroute
             - ingress
             - service