apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:

  - literals:
      - workflow=1
    name: synchronization-config

  - literals:
      - state.0.path="./src/bundles/00-bootstrapping-minimal"
      - state.1.path="./src/bundles/05-bootstrapping-ingress"
      - state.2.path="./src/bundles/10-bootstrapping-utils"
      - state.3.path="./src/bundles/20-baseline-services"
      - state.4.path="./src/bundles/25-baseline-services"
    name: screenplay-bootstrap


resources:
  - flow-bump-up-step.yaml
  - seed-cm-get.yaml
  - seed-job-get.yaml
  - seed-job-patch.yaml
  - seed-job-wait.yaml
  - flow-start-install.yaml