apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-argocd-manager
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - applications
    - appprojects
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - delete
    - patch
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - delete
    - patch
