apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: seed-job-wait
spec:
  entrypoint: exec
  templates:
  - name: exec
    inputs:
      parameters:
        - default: seed-job
          name: argocdAppName
    resource:
      action: get
      #successCondition: status.operationState.phase == "Succeeded"
      #failureCondition: status.operationState.phase in (Failed, Error)
      successCondition: status.sync.status == Synced,status.health.status == Healthy
      failureCondition: status.sync.status in (Failed, Error)
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: {{inputs.parameters.argocdAppName}}
    outputs:
      parameters:
      - name: bootstrapStep
        valueFrom:
          jsonPath: '{.metadata.annotations.de\.noltarium\.bootstrapping/steps}'
      - name: syncStatus
        valueFrom:
          jsonPath: '{.status.sync.status}'
      - name: resources
        valueFrom:
          jqFilter: '[.status.resources | .[] | select( .kind == "Application" ) | .name]'
