# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pdns.md
- op: add
  path: /spec/template/spec/containers/0/envFrom
  value:
    - secretRef:
        name: pdns-api
    - configMapRef:
        name: pdns-config        
- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    - --source=service
    - --source=ingress
    - --provider=pdns
    - --pdns-server=$(pdns_api_url)
    - --pdns-api-key=$(pdns_http_api_key)
    - --txt-owner-id=$(owner_id_for_this_external_dns)
    - --domain-filter=$(pdns_domain_filter) # will make ExternalDNS see only the zones matching provided domain; omit to process all available zones in PowerDNS
    - --log-level=debug
    - --interval=30s