apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
spec:
  destination:
    name: in-cluster
    namespace: rabbitmq
  project: default
  source:
    chart: rabbitmq
    helm:
      releaseName: rabbitmq
    repoURL: https://charts.bitnami.com/bitnamichartslegacy
    targetRevision: 16.0.13
