apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubevirt

resources:

  - https://github.com/kubevirt/kubevirt/releases/download/v0.47.1/kubevirt-operator.yaml
  #- https://github.com/kubevirt/kubevirt/releases/download/v0.47.1/kubevirt-cr.yaml
