---
version: '3'

vars:
  PYTHON_VENVS_BASEDIR: ~/.venvs/
  TASK_COLLECTION_BASE: https://raw.githubusercontent.com/nolte/taskfiles/develop/src
  GIT_ROOT:
    sh: git rev-parse --show-toplevel

includes:
  pre-commit: "{{.TASK_COLLECTION_BASE}}/taskfile-include-pre-commit.yaml"
  mkdocs: "{{.TASK_COLLECTION_BASE}}/taskfile-include-mkdocs.yaml"

  platform: 
    taskfile: .taskfiles/platform.yml
    vars: 
      TASK_COLLECTION_BASE: "https://raw.githubusercontent.com/nolte/taskfiles/develop/src"
  argocd: .taskfiles/argocd.yml
  # serviceset: .taskfiles/Taskfile_servicesets.yml

tasks:
  default:
    cmds:
    - task -l
    silent: true
