apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  labels:
    de.noltarium.workflows/enabled: "true"
spec:
  destination:
    name: in-cluster
    namespace: keycloak
  project: default
  sources:
    - helm:
        releaseName: projectcontour-mixin
        parameters:
          - name: httpProxy.create
            value: "false"
          - name: httpProxy.fqdn
            value: keycloak.smart-home.k8sservices.local
        values: |-
          httpProxy:
            create: false
            fqdn: keycloak.smart-home.k8sservices.local
            tls:
              secretName: cert-manager/wildcard-duckdns-org-tls
            routes:
            - services:
              - name: keycloak
                port: 80
      path: charts/stable/projectcontour-mixin/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
    - helm:
        releaseName: argo-workflow-mixin
        parameters: []
        values: |-
          cmTfStaticEndpoints:
            create: true
          role:
            tfState:
              create: false
              name: argo-workflows-execution
            type: ClusterRole
            vaultInjector:
              create: false
              name: argo-workflows-execution
          roleBinding:
            tfState:
              create: true
            type: Role
            vaultInjector:
              create: true
          serviceAccount:
            create: true
          configurationWorkflows:
            post-install:
              type: terragrunt
              workflow: true
              terraform:
                action: apply
              extraSourceElements:
                - "source /vault/secrets/keycloak"
              extraAnnotations:
                # Load a Secret for Terraform State file access
                vault.hashicorp.com/agent-inject-secret-keycloak: secrets-tf/services/IdentityAccessManagement/users/admin
                vault.hashicorp.com/agent-inject-template-keycloak: |
                  {{- with secret "secrets-tf/services/IdentityAccessManagement/users/admin" -}}
                  export KEYCLOAK_USER={{ .Data.data.username }}
                  export KEYCLOAK_PASSWORD={{ .Data.data.password }}
                  {{- end }}
              source:
                repo: https://github.com/nolte/k8s-home-lab.git
                path: ./src/applications/keycloak/configuration/baseline
                revision: feature/seed-flavors
      path: charts/stable/argo-workflow-mixin/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
    - helm:
        values: |
          service:
            type: ClusterIP
          
          # tls.enabled: true
          production: true
          proxy: edge
          # spi:
          #   hostnameVerificationPolicy: ANY
          
          extraEnvVars:
            - name: TZ
              value: Europe/Berlin
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          auth:
            existingSecret: keycloak-admin-auth
            passwordSecretKey: password
            adminUser: admin
        # parameters: []
      chart: keycloak
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.2.1
    - helm:
        releaseName: external-secrets-manifests
        values: |-
          secretstore:
            create: true
            serviceAccount:
              create: true
          secrets:
            keycloak-admin-auth:
              data:
                - key: services/IdentityAccessManagement/users/admin
                  name: password
                  property: password
      path: charts/stable/external-secrets-manifests/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
