apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  labels:
    de.noltarium.workflows/enabled: "true"
spec:
  destination:
    name: in-cluster
    namespace: keycloak
  project: default
  sources:
  - helm:
      releaseName: projectcontour-mixin
      parameters:
        - name: httpProxy.create
          value: "false"
        - name: httpProxy.fqdn
          value: keycloak.smart-home.k8sservices.local
      values: |-
        httpProxy:
          create: false
          fqdn: keycloak.smart-home.k8sservices.local
          tls:
            secretName: cert-manager/wildcard-duckdns-org-tls  
  - helm:
      releaseName: argo-workflow-mixin
      values: |-
        cmTfStaticEndpoints:
          create: false             

    - chart: keycloak
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 14.2.0
      helm:
        values: |
            service:
              type: ClusterIP
            extraEnv: |
              - name: PROXY_ADDRESS_FORWARDING
                value: "true"
              - name: TZ
                value: Europe/Berlin              
            # ingress:
            #   annotations:
            #     ingress.kubernetes.io/force-ssl-redirect: "true"
            #     kubernetes.io/tls-acme: "true"
            #   rules:
            #     -
            #       # Ingress host
            #       host: '{{ .Release.Name }}.keycloak.example.com'
            #       # Paths for the host
            #       paths:
            #         - path: /
            #           pathType: Prefix
            #   # TLS configuration
            #   tls:
            #     - hosts:
            #         - keycloak.example.com
            #       secretName: ""
        parameters: []
          #- name: keycloak.ingress.enabled
          #  value: "true"
          # - name: keycloak.ingress.annotations."certmanager\.k8s\.io/cluster-issuer"
          #   value: selfsigned-cluster-issuer
          # - name: keycloak.ingress.rules[0].host
          #   value: "keycloak.smart-home.k8sservices.local"
          # - name: keycloak.ingress.tls[0].hosts[0]
          #   value: "keycloak.smart-home.k8sservices.local"
          # - name: keycloak.ingress.tls[0].secretName
          #   value: "keycloak-tls"
