apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonLabels:
  argocd.argoproj.io/instance: seed-job

generatorOptions:
  disableNameSuffixHash: true


resources:
  - ../../../src/applications/project-contour/deploy/argocd
  - ../../../src/applications/kuard/deploy/argocd