apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

labels:
    - includeSelectors: true
      pairs:
        argocd.argoproj.io/instance: seed-job

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1

resources:
  - ../../../src/applications/project-contour/deploy/argocd
