apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
spec:
  destination:
    name: in-cluster
    namespace: node-red
  project: default
  source:
    path: src/applications/node-red/deploy/chart
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master

    helm:
      releaseName: node-red
