apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  destination:
    name: in-cluster
    namespace: argo
  project: cicd
  sources:
  - helm:
      releaseName: projectcontour-mixin
      parameters:
        - name: httpProxy.create
          value: "false"
        - name: httpProxy.fqdn
          value: argo.smart-home.k8sservices.local
      values: |-
        httpProxy:
          create: false
          fqdn: argo.smart-home.k8sservices.local
          tls:
            secretName: cert-manager/wildcard-duckdns-org-tls
    path: charts/stable/projectcontour-mixin/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main
  - helm:
      releaseName: argo-workflow-mixin
      values: |-
        role:
          tfState:
            create: true
            name: argo-workflows-execution
          type: ClusterRole
          vaultInjector:
            create: true
            name: argo-workflows-execution
        roleBinding:
          tfState:
            create: false
          type: Role
          vaultInjector:
            create: false
        serviceAccount:
          annotations: {}
          create: false
          name: argo-workflows-execution
    path: charts/stable/argo-workflow-mixin/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main
  - helm:
      parameters:
        - name: fullnameOverride
          value: argo-workflows
        #- name: argoworkflows.controller.containerRuntimeExecutor
        #  value: k8sapi
        - name: controller.workflowNamespaces[0]
          value: argo
        - name: server.clusterWorkflowTemplates.enabled
          value: 'true'
        - name: controller.workflowDefaults.spec.serviceAccountName
          value: argo-workflows-executer
        - name: server.extraArgs[0]
          value: '--auth-mode=server'
      values: |-
         controller:
           extraEnv:
             - name: ARGO_EXECUTOR_PLUGINS
               value: "true"
      releaseName: argo-workflows
    #path: charts/stable/argo-workflows/
    #repoURL: https://github.com/nolte/helm-charts-repo.git
    #targetRevision: main
    #chart: argo-workflows
    #repoURL: https://nolte.github.io/helm-charts-repo
    #targetRevision: 0.14.1
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.28.2
