apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forecastle
spec:
  destination:
    name: in-cluster
    namespace: forecastle
  project: cicd
  source:
    helm:
      parameters:
        - name: httpProxy.create
          value: 'false'
      valueFiles: []
      values: |
        forecastle:
          forecastle:
            config:
              namespaceSelector:
                any: true
    chart: forecastle
    repoURL: https://nolte.github.io/helm-charts-repo
    targetRevision: 0.2.2        