apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forecastle
spec:
  destination:
    name: in-cluster
    namespace: forecastle
  project: cicd
  sources:
  - helm:
      releaseName: projectcontour-mixin
      parameters:
        - name: httpProxy.create
          value: "false"
      values: |-
        httpProxy:
          create: false
          fqdn: forecastle.smart-home.k8sservices.local
          tls:
            secretName: cert-manager/wildcard-duckdns-org-tls
          routes:
          - services:
            - name: forecastle
              port: 80
    path: charts/stable/projectcontour-mixin/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main
  - helm:
      parameters: []
      valueFiles: []
      values: |
        forecastle:
          config:
            namespaceSelector:
              any: true
    chart: forecastle
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: v1.0.123
