apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: app-cert-wildcard
spec:
  entrypoint: exec
  templates:
    - name: exec
      resource:
        action: apply
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: cert-wildcard
          spec:
            destination:
              name: in-cluster
              namespace: cert-manager
            project: default
            source:
              chart: cert-wildcard
              repoURL: https://nolte.github.io/helm-charts-repo
              targetRevision: 0.1.0
              helm:
                releaseName: cert-wildcard
                