apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: app-cert-wildcard
spec:
  entrypoint: exec
  templates:
    - name: exec
      inputs:
        parameters:
          - name: name-prefix
            default: ""
          - name: destination-name
            default: in-cluster
          - name: cert-wildcard-dns-name
            default: "dev44-just-homestyle.duckdns.org"
          - name: helm-values-filename
            default: "values-reflector.yaml"

      resource:
        action: apply
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: {{inputs.parameters.name-prefix}}cert-wildcard
          spec:
            destination:
              name: {{inputs.parameters.destination-name}}
              namespace: cert-manager
            project: default
            source:
              chart: cert-wildcard
              repoURL: https://nolte.github.io/helm-charts-repo
              targetRevision: 0.3.2
              helm:
                releaseName: cert-wildcard
                valueFiles:
                  - {{inputs.parameters.helm-values-filename}}
                parameters:
                  - name: dnsName
                    value: "{{inputs.parameters.cert-wildcard-dns-name}}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              retry:
                backoff:
                  duration: 10m
                  factor: 1
                  maxDuration: 20m
                limit: 15
              syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true
