apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: app-cert-wildcard
spec:
  entrypoint: exec
  templates:
    - name: exec
      inputs:
        parameters:
          - name: name-prefix
            default: ""
          - name: destination-name
            default: in-cluster
          - name: cert-wildcard-dns-name
            default: "dev44-just-homestyle.duckdns.org"    
      resource:
        action: apply
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: {{inputs.parameters.name-prefix}}cert-wildcard
          spec:
            destination:
              name: {{inputs.parameters.destination-name}}
              namespace: cert-manager
            project: default
            source:
              chart: cert-wildcard
              repoURL: https://nolte.github.io/helm-charts-repo
              targetRevision: 0.1.0
              helm:
                releaseName: cert-wildcard
                parameters:
                  - name: dnsName
                    value: "{{inputs.parameters.cert-wildcard-dns-name}}"
                