apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-argocd-manager
roleRef:
  apiGroup: ''
  kind: Role
  name: argo-workflows-argocd-manager
subjects:
  - apiGroup: ''
    kind: ServiceAccount
    name: argo-workflows-executer
