# https://github.com/codecentric/helm-charts/tree/master/charts/keycloak
# vault:

client_id: admin-cli


httpProxy:
  create: false
  fqdn:  keycloak.smart-home.k8sservices.local
  tls:
    secretName: cert-manager/wildcard-duckdns-org-tls

keycloak: 
  extraEnvFrom: |
    - secretRef:
        name: 'keycloak-admin-user'

terraformModule:
  address: https://github.com/nolte/argo-charts.git//src/applications/keycloak/configuration/baseline?ref=master


argo-workflows-execution:
  cmTfStaticEndpoints:
    create: true

  role:
    tfState:
      create: false
      name: argo-workflows-execution
    type: ClusterRole
    vaultInjector:
      create: false
      name: argo-workflows-execution
  roleBinding:
    tfState:
      create: true
    type: Role
    vaultInjector:
      create: true
  serviceAccount:
    create: true