apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-operator
spec:
  destination:
    name: in-cluster
    namespace: operators
  project: default
  source:
    path: src/applications/kubevirt/deploy/kustomize/operator
    repoURL: https://github.com/nolte/k8s-home-lab.git
    targetRevision: master
