apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: bootstrap-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: exec
  podGC:
    # Pod GC strategy must be one of the following:
    # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
    # * OnPodSuccess - delete pods immediately when pod is successful
    # * OnWorkflowCompletion - delete pods when workflow is completed
    # * OnWorkflowSuccess - delete pods when workflow is successful
    strategy: OnPodSuccess
  templates:
    - name: exec
      steps:
        - - name: get-seed-job-infos
            templateRef:
              name: flow-bump-up-step
              template: exec
