# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: post-sync-powerdns
  labels:
{{ include "powerdns.labels" . | indent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: exec
  templates:
  - name: exec
    steps:                            
      - - name: configure-pdns
          templateRef:
            name: flow-tf-powerdns-baseline
            template: exec
