{{- if .Values.externalSecret.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: fritz-creds
  labels:
    {{- include "common.labels" . | nindent 4 }}  
spec:
  backendType: vault
  data:
    - key: secrets-tf/data/third-party-services/fritz.box/users/monitoring
      name: FRITZ_HOSTNAME
      property: endpoint
    
    - key: secrets-tf/data/third-party-services/fritz.box/users/monitoring
      name: FRITZ_USERNAME
      property: username
    
    - key: secrets-tf/data/third-party-services/fritz.box/users/monitoring
      name: FRITZ_PASSWORD
      property: password     
{{- end }}