apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-33"  
spec:
  destination:
    name: in-cluster
    namespace: gitea
  project: default
  source:
    # chart: gitea
    # repoURL: https://nolte.github.io/helm-charts-repo
    # targetRevision: 1.2.7
    path: charts/stable/gitea/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main
    helm:
      releaseName: gitea
