apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-33"  
spec:
  destination:
    name: in-cluster
    namespace: gitea
  project: default
  source:
    path: src/applications/gitea/deploy/chart
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master
    helm:
      releaseName: gitea
