apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  labels:
    de.noltarium.workflows/enabled: "true"
spec:
  destination:
    name: in-cluster
    namespace: gitea
  project: default
  sources:
    - helm:
        releaseName: projectcontour-mixin
        parameters:
          - name: httpProxy.create
            value: "false"
          - name: httpProxy.fqdn
            value: gitea.smart-home.k8sservices.local
        values: |-
          httpProxy:
            create: false
            fqdn: gitea.smart-home.k8sservices.local
            tls:
              secretName: cert-manager/wildcard-duckdns-org-tls
            routes:
            - services:
              - name: gitea-http
                port: 3000
      path: charts/stable/projectcontour-mixin/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
    - helm:
        releaseName: argo-workflow-mixin
        parameters: []
        values: |-
          cmTfStaticEndpoints:
            create: true
          role:
            tfState:
              create: false
              name: argo-workflows-execution
            type: ClusterRole
            vaultInjector:
              create: false
              name: argo-workflows-execution
          roleBinding:
            tfState:
              create: true
            type: Role
            vaultInjector:
              create: true
          serviceAccount:
            create: true
          configurationWorkflows:
            post-install:
              type: terragrunt
              workflow: true
              terraform:
                action: apply
              extraSourceElements:
                - "source /vault/secrets/gitea"
              extraAnnotations:
                # Load a Secret for Terraform State file access
                vault.hashicorp.com/agent-inject-secret-gitea: secrets-tf/services/IdentityAccessManagement/users/admin
                vault.hashicorp.com/agent-inject-template-gitea: |
                  {{- with secret "secrets-tf/services/IdentityAccessManagement/users/admin" -}}
                  export KEYCLOAK_USER={{ .Data.data.username }}
                  export KEYCLOAK_PASSWORD={{ .Data.data.password }}
                  {{- end }}
              source:
                repo: https://github.com/nolte/k8s-home-lab.git
                path: ./src/applications/gitea/configuration/baseline
                revision: master
      path: charts/stable/argo-workflow-mixin/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main

    - helm:
        releaseName: gitea
        parameters: []
        values: |-
          gitea:
            admin:
              existingSecret: gitea-admin-secret
            config:
              server:
                ROOT_URL: "https://gitea.dev44-just-homestyle.duckdns.org"
            oauth:
              - name: "MyAwesomeGiteaOAuth"
                existingSecret: gitea-oauth
                provider: "openidConnect"
                autoDiscoverUrl: https://keycloak.dev44-just-homestyle.duckdns.org/realms/devops-services/.well-known/openid-configuration
                groupClaimName: groups
                adminGroup: /platform-super-users/gitea-admin-users
      chart: gitea
      repoURL: https://dl.gitea.io/charts/
      targetRevision: 10.1.3

    - helm:
        releaseName: external-secrets-manifests
        parameters: []
        values: |-
          secretstore:
            create: true
            serviceAccount:
              create: true
          secrets:
            gitea-oauth:
              data:
                - key: services/IdentityAccessManagement/clients/gitea
                  name: key
                  property: client_id
                - key: sesecretsrvices/IdentityAccessManagement/clients/gitea
                  name: secret
                  property: client_secret
            gitea-admin-secret:
              data:
                - key: services/gitea/users/admin
                  name: username
                  property: username
                - key: services/gitea/users/admin
                  name: password
                  property: password
                - key: services/gitea/users/admin
                  name: email
                  property: email
      path: charts/stable/external-secrets-manifests/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
