apiVersion: v2
dependencies:
  - name: node-red
    repository: https://k8s-at-home.com/charts/
    version: 9.0.0
description: Preconfigured node-red Deployment
name: node-red
sources: []
type: application
version: 9.0.0