apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuard
spec:
  destination:
    name: in-cluster
    namespace: kuard
  project: default
  source:
    path: src/applications/kuard/deploy/kustomize
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master
