apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:

  #- ../../../../src/applications/cert-wildcard/deploy/workflow-app/
  - ../../../../src/applications/cert-manager-webhook-duckdns/deploy/workflow-app/