apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  #annotations:
  #  argocd.argoproj.io/sync-wave: "30"  
spec:
  destination:
    name: in-cluster
    namespace: minio
  project: default
  source:
    path: src/applications/minio/deploy/kustomize-tenant
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master