apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-50"
spec:
  destination:
    name: in-cluster
    namespace: vault
  project: default
  sources:
  - helm:
      releaseName: projectcontour-mixin
      parameters: []
      #  - name: httpProxy.create
      #    value: "false"
      #  - name: httpProxy.fqdn
      #    value: vault.smart-home.k8sservices.local
      values: |-
        httpProxy:
          create: false
          fqdn: vault.smart-home.k8sservices.local
          tls:
            secretName: cert-manager/wildcard-duckdns-org-tls      
    path: charts/stable/projectcontour-mixin/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main

  - helm:
      releaseName: argo-workflow-mixin
      values: |-
        cmTfStaticEndpoints:
          create: false
        role:
          tfState:
            create: true
            name: argo-workflows-execution
          type: Role
          vaultInjector:
            create: false
            name: argo-workflows-execution
        roleBinding:
          tfState:
            create: true
          type: Role
          vaultInjector:
            create: true
        serviceAccount:
          create: true

    path: charts/stable/argo-workflow-mixin/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main
    
  - helm:
      parameters:
        - name: vault.server.ha.replicas
          value: "1"
        - name: vault.server.raft.enabled
          value: "true"
      values: |-
        server:
          ingress:
            annotations:
              ingress.kubernetes.io/force-ssl-redirect: "true"
              kubernetes.io/tls-acme: "true"
      releaseName: vault
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.24.0

  - helm:
      releaseName: vault-config 
    path: charts/stable/vault/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main
