apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: script-ansible
spec:
  entrypoint: exec
  templates:
  - name: exec
    inputs:
      parameters:
      - name: inventory-repo
        default: git@github.com:nolte/ansible-inventories.git
      - name: inventory-revision
        default: master
      - name: inventory-path
        default: local
      - name: playbook-repo
      - name: playbook-revision
        default: master
      - name: playbook
      - name: playbook-dir
        default: "/src/playbook"
      artifacts:
      - name: inventory-source
        path: /src/inventory
        git:
          repo: "{{inputs.parameters.inventory-repo}}"
          revision: "{{inputs.parameters.inventory-revision}}"
          sshPrivateKeySecret:
            name: git-creds-inventory
            key: id_rsa
      - name: playbook-source
        path: /src/playbook
        git:
          repo: "{{inputs.parameters.playbook-repo}}"
          revision: "{{inputs.parameters.playbook-revision}}"
          sshPrivateKeySecret:
            name: git-creds
            key: id_rsa
    script:
      image: quay.io/ansible/ansible-runner:stable-2.12-latest
      command: [bash]
      env:
        - name: ANSIBLE_INVENTORY
          value: "/src/inventory/{{inputs.parameters.inventory-path}}"
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "false"
        - name: ANSIBLE_PRIVATE_KEY_FILE
          value: /etc/ssh-key/id_rsa
      source: |
        cd /src/playbook
        ansible-runner run {{inputs.parameters.playbook-dir}} --playbook {{inputs.parameters.playbook}}
      volumeMounts:
      - name: ssh-key-volume
        mountPath: "/etc/ssh-key"
    volumes:
    - name: ssh-key-volume
      secret:
        secretName: ansible-ssh
        defaultMode: 256