apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
spec:
  destination:
    name: in-cluster
    namespace: eventsbus
  project: default
  sources:
  - chart: trino
    repoURL:  https://trinodb.github.io/charts/
    targetRevision: 1.41.0
    helm:
      releaseName: trino