apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  # labels:
  #   de.noltarium.workflows/enabled: "true"
spec:
  destination:
    name: in-cluster
    namespace: netbox
  project: default
  sources:
    - helm:
        releaseName: netbox
        parameters: []
        valuesObject:
          postgresql:
            auth:
              existingSecret: "netbox-postgresql"
              secretKeys:
                adminPasswordKey: "postgres-password"
                userPasswordKey: "password"
          redis:
            auth:
              existingSecret: "netbox-redis"
              existingSecretPasswordKey: "redis-password"
          scriptsPersistence:
            enabled: true
          storages:
            default:
              BACKEND: "django.core.files.storage.FileSystemStorage"
      # https://github.com/netbox-community/netbox-chart/blob/main/charts/netbox/values.yaml
      chart: netbox
      repoURL: ghcr.io/netbox-community/netbox-chart
      targetRevision: 8.3.29

  ignoreDifferences:
    - group: v1
      kind: Secret
      name: netbox-postgresql
