apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: cicd
  sources:
    - helm:
        releaseName: argo-workflow-mixin
        parameters: []
        valueFiles: []
      path: charts/stable/argo-workflow-mixin/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
    - path: charts/stable/external-secrets-manifests
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
      helm:
        releaseName: external-secrets-manifests
        valueFiles: []
        # parameters: []
    - path: charts/stable/projectcontour-mixin/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
      helm:
        releaseName: projectcontour-mixin
        valueFiles: []
        # parameters: []
    - helm:
        # parameters: []
        releaseName: argocd
        valueFiles: []
      chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.53.8
    - helm:
        # parameters: []
        releaseName: argocd-apps
        valueFiles: []
      chart: argocd-apps
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 1.4.1
    - repoURL: 'https://github.com/nolte/k8s-home-lab.git'
      targetRevision: feature/seed-flavors
      path: src/applications/argo-cd/deploy
      directory:
        includes: "src/applications/argo-cd/deploy/chart-values/*"
        recurse: false

        #excludes: "*"      
      ref: values