apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: cicd
  source:
    helm:
      parameters: []
      valueFiles:
        - values.yaml
        - values-workflow-support.yaml
    path: src/applications/argo-cd/deploy/chart
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: feature/audio-station