apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: cicd
  sources:
    - helm:
        releaseName: argo-workflow-mixin
        parameters: []
        values: |-
          cmTfStaticEndpoints:
            create: true
          role:
            tfState:
              create: false
              name: argo-workflows-execution
            type: ClusterRole
            vaultInjector:
              create: false
              name: argo-workflows-execution
            executor:
              create: false              
          roleBinding:
            tfState:
              create: true
            type: Role
            vaultInjector:
              create: true
            executor:
              create: true              
          serviceAccount:
            create: true
      path: charts/stable/argo-workflow-mixin/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
    - chart: external-secrets-manifests
      repoURL: https://nolte.github.io/helm-charts-repo/
      targetRevision: 1.0.1
      helm:
        releaseName: external-secrets-manifests
        valueFiles: []
        parameters: []
    - helm:
        parameters: []
        releaseName: argocd
        valueFiles: []
      chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.52.0
    - helm:
        parameters: []
        releaseName: argocd-apps
        valueFiles: []
      chart: argocd-apps
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 1.4.1
