apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-88"  
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    chart: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 19.2.3
    helm:
       # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
      values: |
        grafana:
          enabled: false
      parameters: []