apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-88"  
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
     path: src/applications/kube-prometheus-stack/deploy/chart
     repoURL: https://github.com/nolte/argo-charts.git
     targetRevision: master     
     helm:
       # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
      values: |
        grafana:
          enabled: false
      parameters: []