apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.0.2
    helm:
      # skipCrds: true
       # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
      valuesObject:
        # prometheus:
        #   prometheusSpec:
        #     additionalScrapeConfigs:
        #       - job_name: "http_sd_ips"
        #         http_sd_configs:
        #           - url: http://netbox-operator-app.netbox.svc:80/api/plugins/prometheus-sd/ip-addresses?status=active
        #             refresh_interval: 15s
        #             authorization:
        #               type: "Token"
        #               credentials: "0123456789012345678901234567890123456789"
        grafana:
          enabled: false
          dashboards:
            default:
              fritz-exporter:
                gnetId: 13983
                datasource: Prometheus
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
      parameters: []
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
