---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-minio
spec:
  commonName: minio.smart-home.k8sservices.local
  secretName: tls-minio
  dnsNames:
    # Ingress domain
    - minio.smart-home.k8sservices.local
    # Internal domain
    - minio-hl-svc
    - minio-hl-svc.default.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
