apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: minio-creds-secret
spec:
  backendType: vault
  data:
    - key: secrets-tf/data/services/s3/users/admin
      name: secretkey
      property: secretkey
    - key: secrets-tf/data/services/s3/users/admin
      name: accesskey
      property: accesskey