apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: console-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: console-secret
    creationPolicy: Owner
  data:
  - secretKey: CONSOLE_PBKDF_PASSPHRASE
    remoteRef:
      key: services/s3/users/console-admin
      property: passphrase
  - secretKey: CONSOLE_PBKDF_SALT
    remoteRef:
      key: services/s3/users/console-admin
      property: salt
  - secretKey: CONSOLE_ACCESS_KEY
    remoteRef:
      key: services/s3/users/console-admin
      property: accesskey
  - secretKey: CONSOLE_SECRET_KEY
    remoteRef:
      key: services/s3/users/console-admin
      property: secretkey
#     - key: secrets-tf/data/services/s3/users/console-admin
#       name: CONSOLE_ACCESS_KEY
#       property: accesskey
#     - key: secrets-tf/data/services/s3/users/console-admin
#       name: CONSOLE_SECRET_KEY
#       property: secretkey    
# apiVersion: kubernetes-client.io/v1
# kind: ExternalSecret
# metadata:
#   name: console-secret
# spec:
#   backendType: vault
#   data:
#     - key: secrets-tf/data/services/s3/users/console-admin
#       name: CONSOLE_PBKDF_PASSPHRASE
#       property: passphrase
#     - key: secrets-tf/data/services/s3/users/console-admin
#       name: CONSOLE_PBKDF_SALT
#       property: salt
#     - key: secrets-tf/data/services/s3/users/console-admin
#       name: CONSOLE_ACCESS_KEY
#       property: accesskey
#     - key: secrets-tf/data/services/s3/users/console-admin
#       name: CONSOLE_SECRET_KEY
#       property: secretkey            