apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: tf-minio
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "argo-workflows"
    vault.hashicorp.com/agent-inject-token: "true"
    
    # Load a Secret for Terraform State file access
    vault.hashicorp.com/agent-inject-secret-s3access: secrets-tf/services/s3/users/admin    
# #   "helm.sh/hook": "post-install"    
spec:
  terraformVersion: 0.14.9
  terraformModule:
    address: https://github.com/nolte/argo-charts.git//src/applications/minio/configuration/baseline?ref=feature/applications-structures
  customBackend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "minio-tf"
        in_cluster_config  = true
        namespace = "minio"
      }
    }    
  applyOnCreate: true
  applyOnUpdate: true
  applyOnDelete: true
  ignoreDelete: false
  env:
    - name: MINIO_ENDPOINT
      value: minio.minio.svc
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-creds-secret
          key: secretkey
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-creds-secret
          key: accesskey