apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fritz-exporter
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    helm:
      parameters:
        - name: fullnameOverride
          value: fritz-exporter
      releaseName: fritz-exporter
      values: |
        metrics:
          enabled: true
          serviceMonitor:
            labels:
              release: monitoring

    chart: fritz-exporter
    repoURL: https://nolte.github.io/helm-charts-repo
    targetRevision: 0.2.1    