apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fritz-exporter
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    helm:
      parameters:
        - name: fullnameOverride
          value: fritz-exporter
      releaseName: fritz-exporter
      values: |
        # env: 
        #   using credentials from external/secret (vault)
        #   FRITZ_HOSTNAME: 'xxxx'
        #   FRITZ_USERNAME: 'admin'
        #   FRITZ_PASSWORD: ''
        externalSecret:
          enabled: true
        # envFrom:
        #   - secretRef:
        #       name: fritz-creds
        metrics:
          enabled: true
          serviceMonitor:
            labels:
              release: monitoring

    path: src/applications/fritz-exporter/deploy/chart
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master        