apiVersion: kustomize.config.k8s.io/v1beta1
# commonLabels:
#   argocd.argoproj.io/instance: seed-job
kind: Kustomization
namespace: argocd

generatorOptions:
 disableNameSuffixHash: true


patches:
  - path: ../../kustomization-common/deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1


resources:
  - ../../../src/applications/mopidy/deploy/argocd
  - ../../../src/applications/snapcast-server/deploy/argocd
  - ../../../src/applications/snapcast-client/deploy/argocd
  - ../../../src/applications/upmpdcli/deploy/argocd
