apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-33"  
spec:
  destination:
    name: in-cluster
    namespace: harbor
  project: default
  source:
    path: src/applications/harbor/deploy/chart
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: feature/devops-services-set
    helm:
      releaseName: harbor
