apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-33"  
spec:
  destination:
    name: in-cluster
    namespace: harbor
  project: default
  source:
    chart: harbor
    repoURL: https://nolte.github.io/helm-charts-repo
    targetRevision: 0.2.0
    helm:
      releaseName: harbor
