apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  destination:
    name: in-cluster
    namespace: harbor
  project: default
  sources:
    - helm:
        releaseName: projectcontour-mixin
        parameters: []
        values: |-
          httpProxy:
            create: false
            fqdn: harbor.smart-home.k8sservices.local
            tls:
              secretName: cert-manager/wildcard-duckdns-org-tls
      path: charts/stable/projectcontour-mixin/
      repoURL: https://github.com/nolte/helm-charts-repo.git
      targetRevision: main
    
    - helm:
        parameters: []
      chart: harbor
      repoURL: https://helm.goharbor.io
      targetRevision: 1.11.1
    