apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - delete-ns-rabbitmq-system.yaml

resources:
  - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
