apiVersion: kustomize.config.k8s.io/v1beta1
labels:
    - includeSelectors: true
      pairs:
        argocd.argoproj.io/instance: seed-job
kind: Kustomization
namespace: argocd

generatorOptions:
 disableNameSuffixHash: true


patches:
  - path: ../../kustomization-common/deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1


resources:
  - ../../../src/applications/gitea/deploy/argocd
  - ../../../src/applications/harbor/deploy/argocd
