clustername: smart-home
talosVersion: v1.3.3
kubernetesVersion: v1.26.0
endpoint: https://192.168.178.86:6443
allowSchedulingOnMasters: true
nodes: 
  - hostname: k8ssmarthome01
    ipAddress: 192.168.178.86
    installDisk: /dev/sda
    controlPlane: true

controlPlane:
  patches:
    - |-
        - op: add
          path: /machine/disks
          value:
          - device: /dev/sdX # The name of the disk to use.
            partitions:
              - mountpoint: /var/mnt/storage # Where to mount the partition.


        - op: add
          path: /machine/install/extensions
          value:
            - image: ghcr.io/siderolabs/iscsi-tools:v0.1.1
        
        - op: add
          path: /machine/kubelet/extraMounts
          value:
            - destination: /var/mnt/storage
              type: bind
              source: /var/mnt/storage
              options:
                - bind
                - rshared
                - rw      