apiVersion: v2
appVersion: v2.0.0
description: FritzBox Exporter
name: fritz-exporter
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
- fritz-exporter
- fritzbox
home: https://github.com/k8s-at-home/charts/tree/master/charts/incubator/fritzbox-exporter
sources:
- https://github.com/pdreker/fritz_exporter
maintainers: []
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.0.1
