  # values for https://github.com/nolte/helm-charts-repo/tree/main/charts/stable/external-secrets-manifests
  enabled: true
  secrets:
    argocd-oidc-secret:
      data:
        - key: secrets-tf/data/services/IdentityAccessManagement/clients/argocd
          name: oidc.keycloak.clientSecret
          property: client_secret