projects:
  baseline:
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    description: Baseline Relevant Projects
    destinations:
      - namespace: "*"
        server: "*"
    name: baseline
    namespace: argocd
    sourceRepos:
      - "*"
  seed:
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    description: CICD Seed Jobs
    destinations:
      - namespace: "*"
        server: "*"
    namespace: argocd
    sourceRepos:
      - "*"
  cicd:
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    description: CICD Tools
    destinations:
      - namespace: "*"
        server: "*"
    namespace: argocd
    sourceRepos:
      - "*"
