# values for https://github.com/nolte/helm-charts-repo/tree/main/charts/stable/external-secrets-manifests
enabled: true
secretstore:
  create: true
  serviceAccount:
    create: true
secrets:
  argocd-oidc-secret:
    additionalLabels:
      app.kubernetes.io/part-of: argocd  
    data:
      - key: secrets-tf/data/services/IdentityAccessManagement/clients/argocd
        name: oidc.keycloak.clientSecret
        property: client_secret

