apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-configuration-configs
spec:
  destination:
    name: in-cluster
    namespace: operators
  project: default
  source:
    path: src/applications/namespace-configuration-operator/deploy/kustomize/configs
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master
