apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-vault-baseline
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets","serviceaccounts"]
  verbs: [ "get" ]
