apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

labels:
    - includeSelectors: true
      pairs:
        argocd.argoproj.io/instance: seed-job-rpi

generatorOptions:
  disableNameSuffixHash: true

namePrefix:
  rpi-

patches:
  - path: patch-argocd-destination-cluster.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1

patchesJSON6902:
  - patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value: []
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name:  mopidy.snapcast.server.host
          value: "rpi-snapcast-server"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name:  mopidy.spotify.enabled
          value: "true"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: nodeSelector.task
          value: "gipo"
      - op: add
        path: /spec/source/helm/valueFiles/-
        value: "values-spotify.yaml"
      - op: add
        path: /spec/source/helm/values
        value: |-
          service:
            public:
              type: LoadBalancer
              enabled: true
              annotations:
                metallb.universe.tf/address-pool: mpd-pool
              ports:
                mpd:
                  enabled: true
                  protocol: TCP
                  port: 6600
          ingress:
            main:
              enabled: true
              ingressClassName: nginx
              hosts:
                - host: "mopidy.rpi-just-homestyle.duckdns.org"
                  paths:
                    - path: /
              tls:
                - secretName: wildcard-duckdns-org-tls
                  hosts:
                    - mopidy.rpi-just-homestyle.duckdns.org
    target:
      group: argoproj.io
      kind: Application
      name: mopidy
      version: v1alpha1
  - patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value: []
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name:  hostNetwork
          value: "true"
      # - op: add
      #   path: /spec/source/helm/parameters/-
      #   value:
      #     name: nodeSelector.task
      #     value: "gipo"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: ingress.main.ingressClassName
          value: "nginx"
      - op: add
        path: /spec/source/helm/values
        value: |-
          args: ["-m", "3", "-l", "0", "-h", "192.168.178.108", "-p", "6600", "-P", "1900"]
      - op: add
        path: /spec/source/helm/values
        value: |-
          service:
            main:
              enabled: false
    target:
      group: argoproj.io
      kind: Application
      name: upmpdcli
      version: v1alpha1
  - patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value: []
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: nodeSelector.task
          value: "gipo"
    target:
      group: argoproj.io
      kind: Application
      name: snapcast-server
      version: v1alpha1
  - patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value: []
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: nodeSelector.task
          value: "hifi"
      - op: replace
        path: /spec/source/helm/values
        value: |
          args: ["-h", "rpi-snapcast-server-public","--hostID","rpi-hifi"]
    target:
      group: argoproj.io
      kind: Application
      name: snapcast-client
      version: v1alpha1

  - patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value: []
      - op: replace
        path: /spec/source/helm/values
        value: |
          configInline:
            address-pools:
             - name: default-pool
               protocol: layer2
               addresses:
               - 192.168.178.91-192.168.178.100
             - name: mpd-pool
               protocol: layer2
               addresses:
               - 192.168.178.108/32
             - name: mqtt-pool
               protocol: layer2
               addresses:
               - 192.168.178.109/32
             - name: pihole-svc
               protocol: layer2
               addresses:
               - 192.168.178.110/32
             - name: ingress-pool
               protocol: layer2
               addresses:
               - 192.168.178.111/32
    target:
      group: argoproj.io
      kind: Application
      name: metallb
      version: v1alpha1

  - patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value: []
      - op: add
        path: /spec/source/helm/values
        value: |
          service:
            main:
              enabled: true
              type: LoadBalancer
              annotations:
                metallb.universe.tf/address-pool: mqtt-pool
    target:
      group: argoproj.io
      kind: Application
      name: mosquitto
      version: v1alpha1

  - patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value: []
      - op: replace
        path: /spec/source/helm/values
        value: |
          controller:
            publishService:
              enabled: true
            service:
              externalIPs:
                - 192.168.178.111
              annotations:
                metallb.universe.tf/address-pool: ingress-pool
    target:
      group: argoproj.io
      kind: Application
      name: ingress-nginx
      version: v1alpha1

  - patch: |-
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: homeassistant.hostNetwork
          value: "true"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: homeassistant.env.MQTT_ENDPOINT
          value: "mosquitto.mosquitto.svc"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: homeassistant.env.MOPIDY_ENDPOINT_MPD
          value: "rpi-mopidy-public.audio-station.svc"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: homeassistant.env.MOPIDY_ENDPOINT
          value: "rpi-mopidy.audio-station.svc"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: homeassistant.env.SNAPCAST_ENDPOINT
          value: "rpi-snapcast-server-public.audio-station.svc"
      - op: add
        path: /spec/source/helm/values
        value:  |
          homeassistant:
            ingress:
              main:
                enabled: true
                ingressClassName: nginx
                annotations:
                  nginx.org/websocket-services: home-assistant
                hosts:
                  - host: "homeassistant.rpi-just-homestyle.duckdns.org"
                    paths:
                      - path: /
                tls:
                  - secretName: wildcard-duckdns-org-tls
                    hosts:
                      - homeassistant.rpi-just-homestyle.duckdns.org
    target:
      group: argoproj.io
      kind: Application
      name: home-assistant
      version: v1alpha1

  - patch: |-
      - op: add
        path: /spec/source/helm/values
        value:  |
            adlists:
              - https://adaway.org/hosts.txt
              - https://block.energized.pro/spark/formats/domains.txt
              - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
              - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
              - https://hostsfile.org/Downloads/hosts.txt
              - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
              - https://phishing.army/download/phishing_army_blocklist_extended.txt
              - https://phishing.army/download/phishing_army_blocklist.txt
              - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
              - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
              - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/crowed_list.txt
              - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
              - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
              - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
              - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
              - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist
              - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto
              - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
              - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
              - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails
              - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming
              - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
              - https://urlhaus.abuse.ch/downloads/hostfile/
              - https://v.firebog.net/hosts/Easyprivacy.txt
              - https://v.firebog.net/hosts/Prigent-Ads.txt
              - https://v.firebog.net/hosts/Prigent-Malware.txt
              - https://v.firebog.net/hosts/static/w3kbl.txt
              - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
            serviceDns:
              annotations:
                metallb.universe.tf/allow-shared-ip: pihole-svc
              type: LoadBalancer
            ingress:
              enabled: true
              ingressClassName: nginx
              hosts:
                - "pihole.rpi-just-homestyle.duckdns.org"
              tls:
                - secretName: wildcard-duckdns-org-tls
                  hosts:
                    - pihole.rpi-just-homestyle.duckdns.org
    target:
      group: argoproj.io
      kind: Application
      name: pihole
      version: v1alpha1


resources:
  - ../../../../src/bundles/audio-station
  - ../../../../src/bundles/rpi-specific
  - ../../../../src/bundles/smart-home
