apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #annotations:
  #  argocd.argoproj.io/sync-wave: '-77'
  name: metallb
spec:
  destination:
    name: in-cluster
    namespace: metallb
  project: default
  source:
    helm:
      releaseName: metallb
    path: src/applications/metallb/deploy/chart
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master
    # https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml