apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #annotations:
  #  argocd.argoproj.io/sync-wave: '-77'
  name: metallb
spec:
  destination:
    name: in-cluster
    namespace: metallb
  project: default
  source:
    helm:
      releaseName: metallb
    chart: metallb
    repository: https://charts.bitnami.com/bitnami
    version: 2.5.10
    # https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml