apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: in-cluster
    namespace: metallb-system
  project: default
  source:
    helm:
      releaseName: metallb
      valuesObject:
        speaker:
          # required for services on controllplane
          ignoreExcludeLB: true 
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.15.2
    # https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml
