apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: in-cluster
    namespace: metallb-system
  project: default
  source:
    helm:
      parameters: []
      valueFiles: []
      releaseName: metallb
      values: |-
        speaker:
          # required for services on controllplane
          ignoreExcludeLB: true 
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.9
    # https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml
