address: http://vault.{{ .Release.Namespace }}.svc:8200

httpProxy:
  create: false
  fqdn:  vault.smart-home.k8sservices.local
  tls:
    secretName: cert-manager/wildcard-duckdns-org-tls

argo-workflows-execution:
  cmTfStaticEndpoints:
    create: false

  role:
    tfState:
      create: false
      name: argo-workflows-execution
    type: ClusterRole
    vaultInjector:
      create: false
      name: argo-workflows-execution
  roleBinding:
    tfState:
      create: true
    type: Role
    vaultInjector:
      create: true
  serviceAccount:
    create: true

vault:
  server:
    ingress:
      enabled: false