---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: transport
  annotations:
    # A single RabbitMQ cluster per Knative Eventing installation
    rabbitmq.com/topology-allowed-namespaces: "*"  