apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: transport

secretGenerator:
- name: admin-user-credentials-secret
  literals:
  - username=admin-user
  - password=1f2d1e2e67df

#- name: shovel-config
#  literals:
#  - username=admin-user
#  - password=1f2d1e2e67df


resources:
  - broker.yaml
  - queue-in.yaml
  - queue-out.yaml
  - user.yaml
  - admin.yaml
  - vhost.yaml
  #- shovel.yaml needs any uri
