# for more information, see: https://www.rabbitmq.com/shovel-dynamic.html
---
apiVersion: rabbitmq.com/v1beta1
kind: Shovel
metadata:
  name: shovel-example
spec:
  name: "shovel-example"
  uriSecret:
    name: first-user-user-credentials
  srcQueue: "in-testing-example"
  destQueue: "out-testing-example"
  rabbitmqClusterReference:
    name: transport