
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: first-user
spec:
  tags:
  - management # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
  rabbitmqClusterReference:
    name: transport
