{{- if .Values.externalSecret.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  labels:
    {{- include "argo-cd.labels" (dict "context" .) | nindent 4 }}
spec:
  backendType: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
  data:
    - key: {{ tpl .Values.externalSecret.key . }}
      name: oidc.keycloak.clientSecret
      property: client_secret
{{- end }}