{{- if .Values.externalSecret.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
spec:
  backendType: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
  data:
    - key: {{ tpl .Values.externalSecret.key . }}
      name: oidc.keycloak.clientSecret
      property: client_secret
{{- end }}