{{- if .Values.httpProxy.create }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
spec:
  virtualhost:
    fqdn: {{ tpl .Values.httpProxy.fqdn . }}
    tls:
      secretName: {{ tpl .Values.httpProxy.tls.secretName . }}
  routes:
  - services:
    - name: argocd-server
      port: 80
{{- end }}
