{{- if .Values.workflow.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: post-sync-argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: exec
  templates:
  - name: exec
    steps:
      - - name: configure-argocd
          templateRef:
            name: flow-tf-argocd-fineconfig
            template: exec
{{- end }}