apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-duckdns
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  # hack for ignore changed duration format from 43800h to 43800h0m0s
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
  source:
    # chart: cert-manager-webhook-duckdns
    # repoURL: https://nolte.github.io/helm-charts-repo
    # targetRevision: 0.2.3
    path: charts/stable/cert-manager-webhook-duckdns/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: feature/2023-q1  

    helm:
      releaseName: cert-manager-webhook-duckdns
      parameters:
        - name: certmanagerwebhookduckdns.fullnameOverride
          value: "cert-manager-webhook-duckdns"
        # - name: certmanagerwebhookduckdns.clusterIssuer.email
        #   value: "{{inputs.parameters.issuerEmail}}"
        - name: certmanagerwebhookduckdns.clusterIssuer.production.create
          value: "false"
        - name: certmanagerwebhookduckdns.clusterIssuer.staging.create
          value: "false"
        - name: certmanagerwebhookduckdns.secret.existingSecret
          value: "true"
        - name: certmanagerwebhookduckdns.secret.existingSecretName
          value: "duckdns-token"
        #- name: externalsecrets.enabled
        #  value: "false"              
