apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-duckdns-workflows
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  # hack for ignore changed duration format from 43800h to 43800h0m0s
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
  sources:
    
    - chart: external-secrets-manifests
      repoURL: https://nolte.github.io/helm-charts-repo/
      targetRevision: 1.0.1
      helm:
        releaseName: external-secrets-manifests
        values: |
          enabled: true
          secretstore:
            create: true
            serviceAccount:
              create: true
          secrets:
            duckdns-token:
              data:
                - key: third-party-services/duckdns.org/api
                  name: token
                  property: token

    - path: src/applications/cert-manager-webhook-duckdns/deploy/workflow-app
      repoURL: https://github.com/nolte/k8s-home-lab.git
      targetRevision: feature/seed-flavors
