apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-duckdns
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  # hack for ignore changed duration format from 43800h to 43800h0m0s
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
  sources:
    - path: deploy/cert-manager-webhook-duckdns
      repoURL: https://github.com/ebrianne/cert-manager-webhook-duckdns.git
      targetRevision: "v1.2.3"
      helm:
        releaseName: cert-manager-webhook-duckdns
        valuesObject:
          fullnameOverride: cert-manager-webhook-duckdns
          clusterIssuer:
            email: no-replay@local
            staging:
              create: true
            production:
              create: true
          secret:
            existingSecret: true
            existingSecretName: duckdns-token

    - chart: external-secrets-manifests
      repoURL: https://nolte.github.io/helm-charts-repo/
      targetRevision: 1.1.0
      helm:
        releaseName: external-secrets-manifests
        values: |
          secretstore:
            create: true
            serviceAccount:
              create: true
          secrets:
            duckdns-token:
              data:
                - key: third-party-services/duckdns.org/api
                  name: token
                  property: token
