apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-duckdns
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  # hack for ignore changed duration format from 43800h to 43800h0m0s
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
  sources:
    - chart: cert-manager-webhook-duckdns
      repoURL: https://ebrianne.github.io/helm-charts
      targetRevision: 1.2.4
      helm:
        releaseName: cert-manager-webhook-duckdns
        parameters:
          - name: fullnameOverride
            value: "cert-manager-webhook-duckdns"
          # - name: certmanagerwebhookduckdns.clusterIssuer.email
          #   value: "{{inputs.parameters.issuerEmail}}"
          - name: clusterIssuer.production.create
            value: "false"
          - name: clusterIssuer.staging.create
            value: "false"
          - name: secret.existingSecret
            value: "true"
          - name: secret.existingSecretName
            value: "duckdns-token"
          #- name: externalsecrets.enabled
          #  value: "false" 
        values: |
          fullnameOverride: cert-manager-webhook-duckdns
          clusterIssuer:
            staging:
              create: true
            production:
              create: true
          secret:
            existingSecret: true
            existingSecretName: duckdns-token                      
    - chart: external-secrets-manifests
      repoURL: https://nolte.github.io/helm-charts-repo/
      targetRevision: 1.0.0
      helm:
        releaseName: external-secrets-manifests
        values: |
          enabled: true
          secretstore:
            create: true
            serviceAccount:
              create: true
          secrets:
            duckdns-token:
              data:
                - key: third-party-services/duckdns.org/api
                  name: token
                  property: token