apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
spec:
  destination:
    name: in-cluster
    namespace: zigbee2mqtt
  project: default
  sources:
  - chart: zigbee2mqtt
    # https://github.com/truecharts/charts/blob/master/charts/stable/zigbee2mqtt/values.yaml
    repoURL: https://charts.truecharts.org/
    targetRevision: 8.0.17
    helm:
      releaseName: zigbee2mqtt
      values: |

        fallbackDefaults:
          # -- Default PVC Size
          pvcSize: 5Gi
          # -- Default VCT Size
          vctSize: 5Gi


        persistence:
          configmap-vol:
            enabled: true
            type: configmap
            objectName: zigbee2mqtt-extra-config
            expandObjectName: false
            mountPath: /mnt/data
            items:
              - key: devices.yaml
                path: devices.yaml
              - key: groups.yaml
                path: groups.yaml

        configmap:
          extra-config:
            enabled: true
            namespace: zigbee2mqtt
            annotations:
              reloader.stakater.com/auto: "true"
            data:
              devices.yaml: |
                '0x8cf681fffe28e088':
                  friendly_name: 'workroom_blind_01'
                '0x04cd15fffe382c92':
                  friendly_name: 'workroom_blind_02'
                '0x18fc2600000120ab':
                  friendly_name: 'bedroom_window_contact_01'
                '0x18fc260000079e3e':
                  friendly_name: 'window_contact_02'
                '0x18fc260000067d50':
                  friendly_name: 'window_contact_03'
                '0x18fc260000076b59':
                  friendly_name: 'window_contact_04'
                '0x040d84fffe8d433e':
                  # ikea 4 button
                  friendly_name: 'remote_01'
                '0x8cf681fffe338337':
                  friendly_name: 'remote_02'
                '0x8cf681fffe36d4fc':
                  friendly_name: 'remote_03'
                '0x0017880106367978':
                  friendly_name: 'remote_04'
                '0x00178801086a34a7':
                  friendly_name: 'remote_05'
                '0x00124b002934f92c':
                  friendly_name: 'snzb_02_01'
                '0x00124b00292c174d':
                  friendly_name: 'snzb_02_02'
                '0x00124b00292c19a9':
                  friendly_name: 'snzb_02_03'
                '0x00124b00292c4376':
                  friendly_name: 'snzb_02_04'
              groups.yaml: |
                '1':
                  friendly_name: 'blind_workroom'
                  devices:
                    - '0x8cf681fffe28e088'
                    - '0x04cd15fffe382c92'
        deviceList:
          - name: zigbee
            enabled: true
            type: device
            hostPath: /dev/ttyACM0 # /dev/ttyUSB0
            # readOnly: true
        securityContext:
          container:
            privileged: true
        workload:
          main:
            podSpec:
              containers:
                main:
                  env:
                    ZIGBEE2MQTT_DATA: "/data"
                    ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "{{ .Values.service.main.ports.main.port }}"
                    # User defined
                    USE_CUSTOM_CONFIG_FILE: false
                    # This values are required for the autogenerated file to work.
                    ZIGBEE2MQTT_CONFIG_EXPIRIMENTAL_NEW_API: true
                    ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: true
                    ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://192.168.178.23:31883"
                    ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
                    ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "/dev/ttyACM0"
                    ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: "ezsp"
                    ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: true
                    ZIGBEE2MQTT_CONFIG_GROUPS: /mnt/data/groups.yaml
                    ZIGBEE2MQTT_CONFIG_DEVICES: /mnt/data/devices.yaml
