apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
spec:
  destination:
    name: in-cluster
    namespace: zigbee2mqtt
  project: default
  source:
    chart: zigbee2mqtt
    repoURL: https://charts.truecharts.org/
    targetRevision: 8.0.11
    helm:
      releaseName: zigbee2mqtt
      # https://github.com/arangodb/kube-arangodb/blob/1.2.32/chart/kube-arangodb/values.yaml
      values: |
        deviceList:
          - name: zigbee
            enabled: true
            type: device
            hostPath: /dev/ttyACM0 # /dev/ttyUSB0
            # readOnly: true
        securityContext:
          container:
            privileged: true
        workload:
          main:
            podSpec:
              containers:
                main:
                  env:
                    ZIGBEE2MQTT_DATA: "/data"
                    ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "{{ .Values.service.main.ports.main.port }}"
                    # User defined
                    USE_CUSTOM_CONFIG_FILE: false
                    # This values are required for the autogenerated file to work.
                    ZIGBEE2MQTT_CONFIG_EXPIRIMENTAL_NEW_API: true
                    ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: true
                    ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://192.168.178.23:31883"
                    ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
                    ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "/dev/ttyACM0"
                    ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: "ezsp"
                    ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: true
