apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  argocd.argoproj.io/instance: seed-job
kind: Kustomization
namespace: argocd

generatorOptions:
 disableNameSuffixHash: true


patches:
  - path: deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1

patchesJSON6902:
  - patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value: []
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.defaultRules.create
          value: "false"
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.alertmanager.enabled
          value: "false"
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.kubeEtcd.enabled
          value: "false"
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.kubeApiServer.enabled
          value: "false"   
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.kubeProxy.enabled
          value: "false"
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.nodeExporter.enabled
          value: "false"
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.kubelet.enabled
          value: "false"
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.coreDns.enabled
          value: "false"
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.kubeControllerManager.enabled
          value: "false"          
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.kubeScheduler.enabled
          value: "false"          
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.kubeStateMetrics.enabled
          value: "false"            
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.grafana.defaultDashboardsEnabled
          value: "false"
      - op: add
        path: /spec/source/helm/parameters/-
        value:             
          name:  kube-prometheus-stack.grafana.enabled
          value: "true"
    target:
      group: argoproj.io
      kind: Application
      name: monitoring
      version: v1alpha1


resources:
  - ../../../src/applications/argo-cd/deploy/argocd
  - ../../../src/applications/monitoring/deploy/argocd
  - ../../../src/applications/fritz-exporter/deploy/argocd
  - ../../../src/applications/blackbox-exporter/deploy/argocd
  - ../../../src/applications/speedtest-exporter/deploy/argocd
  - ../../../src/applications/blackbox-exporter/deploy/argocd
