apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow-certmanager-duckdns
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: src/applications/cert-manager-webhook-duckdns/deploy/workflow-app
    repoURL: https://github.com/nolte/k8s-home-lab.git
    targetRevision: master

