apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: ../../../../kustomization-common/deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1

resources:
  - application.yaml
