{{- if .Values.certificate.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant
  labels:
    {{- include "common.labels" . | nindent 4 }}  
spec:
  secretName: home-assistant-tls
  dnsNames:
  - home-assistant.smart-home.k8sservices.local
  - home-assistant.home-assistant.svc
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
