{{- $dot := . -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-creds
  labels:
    {{- include "common.labels" . | nindent 4 }}  
spec:
  backendType: vault
  data:
{{- toYaml .Values.assistantCreds.data | nindent 4 }}