{{- if .Values.httpProxy.create }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: home-assistant
  labels:
    {{- include "common.labels" . | nindent 4 }}  
spec:
  virtualhost:
    fqdn: {{ tpl .Values.httpProxy.fqdn . }}
    tls:
      secretName: {{ tpl .Values.httpProxy.tls.secretName . }}
  routes:
  - services:
    - name: home-assistant
      port: 8123
  - conditions:
    - prefix: /api
    enableWebsockets: true # Setting this to true enables websocket for all paths that match /websocket
    services:
    - name: home-assistant
      port: 8123
{{- end }}
