apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  argocd.argoproj.io/instance: seed-job
kind: Kustomization
namespace: argocd

generatorOptions:
 disableNameSuffixHash: true


patches:
  - path: ../deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1


resources:
  - ../../../src/bundles/20-baseline-services
  - ../../../src/applications/keycloak/deploy/argocd
  - ../../../src/applications/powerdns/deploy/argocd
  - ../../../src/applications/external-dns/deploy/argocd
  - ../../../src/applications/velero/deploy/argocd
