apiVersion: kustomize.config.k8s.io/v1beta1
labels:
    - includeSelectors: true
      pairs:
        argocd.argoproj.io/instance: seed-job
kind: Kustomization
namespace: argocd

generatorOptions:
 disableNameSuffixHash: true


patches:
  - path: ../../kustomization-common/deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1
  - target:
      kind: Application
      labelSelector: de.noltarium.workflows/enabled=true
    path: ../../kustomization-common/app-namespace-workflow-support-patch.yaml


patchesJson6902:
- target:
    group: argoproj.io
    kind: Application
    name: monitoring
    version: v1alpha1
  path: ../../kustomization-common/deployment-serverside-patch.yaml




resources:
  - ../../../src/bundles/20-baseline-services
  - ../../../src/applications/keycloak/deploy/argocd
  - ../../../src/applications/powerdns/deploy/argocd
  - ../../../src/applications/external-dns/deploy/argocd
  - ../../../src/applications/velero/deploy/argocd
