apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
spec:
  destination:
    name: in-cluster
    namespace: reflector
  project: default
  source:
    helm:
      releaseName: reflector
    chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: 6.1.47       