apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubevirt

resources:
 - https://github.com/kubevirt/kubevirt/releases/download/v1.5.0/kubevirt-cr.yaml
 #- https://kubevirt.io/labs/manifests/vm.yaml
