apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: beer-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Beer Source"
    description: "Retrieve a random beer from catalog"
    properties:
      period:
        title: Period
        description: The interval between two events
        type: integer
        default: 1000
  types:
    out:
      mediaType: application/json
  flow:
    from:
      uri: timer:tick
      parameters:
        period: "#property:period"
      steps:
      - to: "https://random-data-api.com/api/beer/random_beer"
      #- to: "knative:channel/mychannel"
      - to: "kamelet:sink"
---
#apiVersion: camel.apache.org/v1alpha1
#kind: KameletBinding
#metadata:
#  name: beer-source-to-channel
#spec:
#  source:
#    ref:
#      kind: Kamelet
#      apiVersion: camel.apache.org/v1alpha1
#      name: beer-source
#  sink:
#    ref:
#      kind: Channel
#      apiVersion: messaging.knative.dev/v1
#      name: mychannel
