# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sync
spec:
  entrypoint: sync
  arguments:
    parameters:
    - name: appName
  templates:  
  - name: sync
    inputs:
      parameters:
      - name: appName
        value: "{{workflow.parameters.appName}}"
    container:
      image: argoproj/argocd:v1.8.4 #TODO: switch to smaller one
      command: [sh, -c]
      args: ["argocd app sync {{inputs.parameters.appName}} --insecure"]
      envFrom:
      - configMapRef:
          name: argocd-auth-info
      - secretRef:
          name: argocd-auth