apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-wildcard
  annotations:
    argocd.argoproj.io/sync-wave: "-70"
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  sources:
    - chart: cert-wildcard
      repoURL: https://nolte.github.io/helm-charts-repo/
      targetRevision: "0.3.2"
      helm:
        releaseName: cert-wildcard
        valueFiles:
          - values-contour-tls-delegate.yaml
        valuesObject:
          dnsName: please.change.me.local
