apiVersion: v2
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 4.2.2
  - name: argo-workflow-mixin
    condition: workflow.enabled
    repository: https://nolte.github.io/helm-charts-repo/
    version: 0.2.0
    alias: argo-workflows-execution    
description: Preconfigured ArgoCD Deployment
name: argo-cd
sources:
  - https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd
type: application
version: 0.2.2