apiVersion: v2
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 4.5.3
  - name: argo-workflow-mixin
    condition: workflow.enabled
    repository: https://nolte.github.io/helm-charts-repo/
    version: 0.4.3
    alias: argo-workflows-execution
  - name: external-secrets-manifests
    version: 0.1.3
    repository: https://nolte.github.io/helm-charts-repo/
    alias: externalsecrets
    condition: externalsecrets.enabled
description: Preconfigured ArgoCD Deployment
name: argo-cd
sources:
  - https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd
type: application
version: 0.2.2