argo-cd:
  server:
    additionalApplications:
      - additionalAnnotations:
          argocd.argoproj.io/sync-wave: '-100'
          de.noltarium.bootstrapping/steps: 0
        additionalLabels: {}
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        name: seed-job
        namespace: argocd
        project: cicd
        source:
          path: src/bundles/light-monitoring
          repoURL: https://github.com/nolte/argo-charts.git
          targetRevision: master
        syncPolicy:
          automated:
            prune: true
            selfHeal: true