argocd-apps:
  applications: 
      - additionalAnnotations:
          argocd.argoproj.io/sync-wave: '-90'
        additionalLabels: {}
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        name: bootstrap-screenplay
        namespace: argocd
        project: cicd
        source:
          path: src/clusters/screenplay/dev-kind-powerdns
          repoURL: https://github.com/nolte/argo-charts.git
          targetRevision: master
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
      - additionalAnnotations:
          argocd.argoproj.io/sync-wave: '-100'
          de.noltarium.bootstrapping/steps: 0
        additionalLabels: {}
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        name: seed-job
        namespace: argocd
        project: cicd
        source:
          path: src/bundles/00-bootstrapping-minimal
          repoURL: https://github.com/nolte/argo-charts.git
          targetRevision: master
        syncPolicy:
          automated:
            prune: true
            selfHeal: true