argo-workflows-execution:
  cmTfStaticEndpoints:
    create: true

  role:
    tfState:
      create: false
      name: argo-workflows-execution
    type: ClusterRole
    vaultInjector:
      create: false
      name: argo-workflows-execution
  roleBinding:
    tfState:
      create: true
    type: Role
    vaultInjector:
      create: true
  serviceAccount:
    create: true

  configurationWorkflows:
    post-install:
      type: terragrunt
      workflow: true
      terraform:
        action: apply
      extraSourceElements:
        - "source /vault/secrets/keycloak"
      extraAnnotations:
        vault.hashicorp.com/agent-inject-secret-keycloak: secrets-tf/services/IdentityAccessManagement/users/admin
        vault.hashicorp.com/agent-inject-template-keycloak: |
          {{- with secret "secrets-tf/services/IdentityAccessManagement/users/admin" -}}
          export KEYCLOAK_USER={{ .Data.data.username }}
          export KEYCLOAK_PASSWORD={{ .Data.data.password }}
          {{- end }}
      source:
        repo: https://github.com/nolte/argo-charts.git
        path: ../src/applications/argo-cd/configuration/fineconf
        revision: feature/audio-station

workflow:
  enabled: true

externalsecrets:
  enabled: true
  secrets:
    argocd-oidc-secret:
      data:
        - key: secrets-tf/data/services/IdentityAccessManagement/clients/argocd
          name: oidc.keycloak.clientSecret
          property: client_secret

argo-cd:
  apiVersionOverrides:
    certmanager: cert-manager.io/v1
  server:
    config:
      url: https://argocd.dev44-just-homestyle.duckdns.org
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.dev44-just-homestyle.duckdns.org/auth/realms/devops-services
        clientID: argocd
        clientSecret: $argocd-oidc-secret:oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
    rbacConfig:
      policy.csv: |
        # Grant all members of the group 'my-org:team-alpha; the ability to sync apps in 'my-project'
        # p, my-org:team-alpha, applications, sync, my-project/*, allow
        # Grant all members of 'my-org:team-beta' admins
        g, /platform-super-users/argocd-admin-users, role:admin        