apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed-job
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: src/clusters/talos-smart-home
    repoURL: https://github.com/nolte/k8s-home-lab.git
    targetRevision: feature/seed-flavors
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
