apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
spec:
  destination:
    name: in-cluster
    namespace: velero
  project: default
  source:
    chart: velero
    helm:
      releaseName: velero
      parameters:
        - name: backupsEnabled
          value: 'false'
        - name: snapshotsEnabled
          value: 'false'
    repoURL: https://vmware-tanzu.github.io/helm-charts
    # https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero
    targetRevision: 11.0.0
