{
 "title": "Fritz! Exporter",
 "description": "Demo Dashboard for stats from fritz_exporter (https://github.com/pdreker/fritzbox_exporter)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serial",
    "label": "Serial Number",
    "query": {
     "query": "label_values(fritz_update_available, serial)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DSL Link Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wan_phys_link_status{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "DSL Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_status{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "PPP Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_ppp_connection_state{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "PPP Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fritz_uptime_seconds_total{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "DSL Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_status_enabled{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "LAN Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_lan_status{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "LAN Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_lan_status_enabled{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "Update available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fritz_update_available{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "Known devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fritz_known_devices_count{serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fritz_uptime_seconds_total{serial=\"$serial\"}"
    }
   ]
  },
  { "title": "LAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "LAN bytes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_lan_data_bytes_total{serial=\"$serial\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "LAN packets/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_lan_packet_count_total{serial=\"$serial\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  { "title": "Wifi 2.4GHz", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Wifi Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"2.4GHz\"}",
     "legendFormat": "{{ enabled }}"
    }
   ]
  },
  {
   "title": "SSID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"2.4GHz\"}",
     "legendFormat": "{{ ssid }}"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_channel{serial=\"$serial\",wifi_name=\"2.4GHz\"}"
    }
   ]
  },
  {
   "title": "Packets/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_wifi_packets_count_total{serial=\"$serial\",wifi_name=\"2.4GHz\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{serial=\"$serial\",wifi_name=\"2.4GHz\"}",
     "legendFormat": "associations"
    }
   ]
  },
  {
   "title": "Wifi Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"2.4GHz\"}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{serial=\"$serial\",wifi_name=\"2.4GHz\"}",
     "legendFormat": "associations"
    }
   ]
  },
  {
   "title": "Wifi standard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"2.4GHz\"}",
     "legendFormat": "802.11{{ standard }}"
    }
   ]
  },
  { "title": "Wifi 5 GHz", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Wifi Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"5GHz\"}",
     "legendFormat": "{{ enabled }}"
    }
   ]
  },
  {
   "title": "SSID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"5GHz\"}",
     "legendFormat": "{{ ssid }}"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_channel{serial=\"$serial\",wifi_name=\"5GHz\"}"
    }
   ]
  },
  {
   "title": "Packets/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_wifi_packets_count_total{serial=\"$serial\",wifi_name=\"5GHz\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{serial=\"$serial\",wifi_name=\"5GHz\"}",
     "legendFormat": "associations"
    }
   ]
  },
  {
   "title": "Wifi Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"5GHz\"}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{serial=\"$serial\",wifi_name=\"5GHz\"}",
     "legendFormat": "associations"
    }
   ]
  },
  {
   "title": "Wifi standard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"5GHz\"}",
     "legendFormat": "802.11{{ standard }}"
    }
   ]
  },
  { "title": "Wifi Guest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Wifi Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\",wifi_name=\"Guest\"}",
     "legendFormat": "{{ enabled }}"
    }
   ]
  },
  {
   "title": "SSID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\", wifi_name=\"Guest\"}",
     "legendFormat": "{{ ssid }}"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_channel{serial=\"$serial\", wifi_name=\"Guest\"}"
    }
   ]
  },
  {
   "title": "Packets/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_wifi_packets_count_total{serial=\"$serial\", wifi_name=\"Guest\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{serial=\"$serial\", wifi_name=\"Guest\"}",
     "legendFormat": "associations"
    }
   ]
  },
  {
   "title": "Wifi Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\", wifi_name=\"Guest\"}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{serial=\"$serial\", wifi_name=\"Guest\"}",
     "legendFormat": "associations"
    }
   ]
  },
  {
   "title": "Wifi standard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{serial=\"$serial\", wifi_name=\"Guest\"}",
     "legendFormat": "802.11{{ standard }}"
    }
   ]
  },
  { "title": "WAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "WAN bytes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_wan_data_bytes_total{serial=\"$serial\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "WAN packets/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_wan_data_packets_count_total{serial=\"$serial\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  { "title": "DSL Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Current linkrate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_datarate_kbps{type=\"curr\", serial=\"$serial\"}",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "DSL attenuation",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "-fritz_dsl_attenuation_dB", "legendFormat": "{{ direction }}" }
   ]
  },
  {
   "title": "DSL noise margin",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_noise_margin_dB{serial=\"$serial\"}",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Max downstream linkrate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_datarate_kbps{direction=\"rx\", type=\"max\", serial=\"$serial\"}"
    }
   ]
  },
  {
   "title": "Max upstream linkrate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_datarate_kbps{direction=\"tx\", type=\"max\", serial=\"$serial\"}"
    }
   ]
  }
 ]
}