apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mopidy
spec:
  destination:
    name: in-cluster
    namespace: audio-station
  project: default
  source:
    path: charts/stable/mopidy
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: feature/multi-room-audio