apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mopidy
spec:
  destination:
    name: in-cluster
    namespace: audio-station
  project: default
  source:
    chart: mopidy
    repoURL: https://nolte.github.io/helm-charts-repo
    targetRevision: 0.1.1      
    helm:
      parameters: []
      valueFiles: [] 