apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-contour
spec:
  destination:
    name: in-cluster
    namespace: projectcontour
  project: default
  source:
    helm:
      releaseName: contour
      parameters: []
      values: |
        envoy:
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/address-pool: production-public-ips
              
        #contour:
        #  extraArgs:
        #    - --ingress-status-address=192.168.178.105
        #  manageCRDs: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.5.10
    chart: contour
