apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-contour
spec:
  destination:
    name: in-cluster
    namespace: projectcontour
  project: default
  source:
    helm:
      parameters:
        - name: envoy.service.type
          value: NodePort
      releaseName: contour
      values: |
        contour:
          manageCRDs: true
          extraArgs:
            - --ingress-status-address=192.168.0.39
    # path: src/applications/project-contour/deploy/chart
    # repoURL: https://github.com/nolte/argo-charts.git
    # targetRevision: master    
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.0.0    
    chart: contour    