apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-contour
spec:
  destination:
    name: in-cluster
    namespace: projectcontour
  project: default
  source:
    helm:
      releaseName: contour
      values: |
        envoy:
          service:
            type: NodePort
          containerSecurityContext:
            enabled: "false"
            runAsUser: "0"
          extraEnvVars:
            - name: ENVOY_UID
              value: "0"
        contour:
          extraArgs:
            - --ingress-status-address=192.168.178.42
          manageCRDs: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.8.2    
    chart: contour    