apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-contour
spec:
  destination:
    name: in-cluster
    namespace: projectcontour
  project: default
  source:
    helm:
      parameters:
#        - name: envoy.hostNetwork
#          value: "true"
        - name: envoy.service.type
          value: NodePort
        - name: envoy.containerSecurityContext.enabled
          value: "true"
        - name: envoy.containerSecurityContext.runAsUser
          value: "0"
        - name: envoy.extraEnvVars[0].name
          value: "ENVOY_UID"
        - name: envoy.extraEnvVars[0].value
          value: "0"
        - name: contour.extraArgs[0]
          value: "--ingress-status-address=192.168.178.21"          
      releaseName: contour
      values: |
        contour:
          manageCRDs: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.0.1    
    chart: contour    