apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{.Values.certmanagerwebhookduckdns.secret.existingSecretName}}
  labels:
    app: {{ include "cert-manager-webhook-duckdns.name" . }}
    chart: {{ include "cert-manager-webhook-duckdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backendType: vault
  data:
    - key: secrets-tf/data/third-party-services/duckdns.org/api
      name: token
      property: token