apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    helm:
      releaseName: prometheus-blackbox-exporter
    chart: prometheus-blackbox-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 7.12.0       