apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  destination:
    name: in-cluster
    namespace: home-assistant
  project: default
  sources:
  - path: charts/stable/projectcontour-mixin/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main
    helm:
     releaseName: projectcontour-mixin
     parameters:
       - name: httpProxy.create
         value: "false"
       - name: httpProxy.fqdn
         value: home-assistant.smart-home.k8sservices.local
     values: |-
       httpProxy:
         create: false
         fqdn: home-assistant.smart-home.k8sservices.local
         tls:
           secretName: cert-manager/wildcard-duckdns-org-tls
         routes:
           - services:
             - name: home-assistant
               port: 8123
           - conditions:
             - prefix: /api
             enableWebsockets: true # Setting this to true enables websocket for all paths that match /websocket
             services:
             - name: home-assistant
               port: 8123

  - chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 1.5.1
    helm:
      releaseName: home-assistant
      parameters: []
      values: |
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: 2023.2.5
        service:
          main:
            ports:
              http:
                port: 8123
        controller:
          type: statefulset
          annotations:
            reloader.stakater.com/auto: "true"
        hostNetwork: true
        resources:
          requests:
            cpu: 126m
            memory: 411M
          limits:
            memory: 4417M

        persistence:
          config:
            enabled: false
            type: hostPath
            mountPath: /config
            hostPath: /var/mnt/storage/home-assistant
            