apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  destination:
    name: in-cluster
    namespace: home-assistant
  project: default
  source:
    #chart: home-assistant
    #repoURL: https://nolte.github.io/helm-charts-repo
    #targetRevision: 1.0.0  
    path: charts/stable/home-assistant
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: feature/multi-room-audio    
    helm:
      releaseName: home-assistant
      parameters: []
      valueFiles:
      - values-gitsync.yaml