apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  destination:
    name: in-cluster
    namespace: home-assistant
  project: default
  source:
    chart: home-assistant
    repoURL: https://nolte.github.io/helm-charts-repo
    targetRevision: 1.3.1  
    helm:
      releaseName: home-assistant
      parameters: []
      valueFiles:
      - values-gitsync.yaml