apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  destination:
    name: in-cluster
    namespace: home-assistant
  project: default
  sources:
  - path: charts/stable/projectcontour-mixin/
    repoURL: https://github.com/nolte/helm-charts-repo.git
    targetRevision: main
    helm:
     releaseName: projectcontour-mixin
     parameters:
       - name: httpProxy.create
         value: "false"
       - name: httpProxy.fqdn
         value: home-assistant.smart-home.k8sservices.local
     values: |-
       httpProxy:
         create: false
         fqdn: home-assistant.smart-home.k8sservices.local
         tls:
           secretName: cert-manager/wildcard-duckdns-org-tls
         routes:
           - services:
             - name: home-assistant
               port: 8123
           - conditions:
             - prefix: /api
             enableWebsockets: true # Setting this to true enables websocket for all paths that match /websocket
             services:
             - name: home-assistant
               port: 8123

  - chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 2.6.0
    helm:
      releaseName: home-assistant
      parameters: []
      values: |

        service:
          main:
            ports:
              http:
                port: 8123
        controllers:
            main:
              containers:
                main:
                  image:
                    repository: ghcr.io/home-assistant/home-assistant
                    tag: 2023.12.1

              type: statefulset
              annotations:
                reloader.stakater.com/auto: "true"

            # resources:
            #   requests:
            #     cpu: 126m
            #     memory: 411M
            #   limits:
            #     memory: 4417M

        defaultPodOptions:
          hostNetwork: true

        persistence:
          config:
            enabled: true
            #type: emptyDir
            type: hostPath
            globalMounts:
              - path: /config
                readOnly: false
            hostPath: /var/mnt/storage/home-assistant
        # persistence:
        #   # Configure the main configuration storage location
        #   config:
        #     enabled: true
        #     existingClaim: home-assistant-config
        #     globalMounts:
        #       - path: /config
