apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-user
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    helm.sh/chart: {{ include "keycloak.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  backendType: vault
  data:
    - key: secrets-tf/data/services/IdentityAccessManagement/users/admin
      name: KEYCLOAK_PASSWORD
      property: password
    - key: secrets-tf/data/services/IdentityAccessManagement/users/admin
      name: KEYCLOAK_USER
      property: username      