apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  argocd.argoproj.io/instance: seed-job
kind: Kustomization
namespace: argocd

generatorOptions:
 disableNameSuffixHash: true

patches:
  - path: ../../kustomization-common/deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1


patchesJSON6902:
- target:
      group: argoproj.io
      kind: Application
      version: v1alpha1
      name: vault
  patch: |-
    - op: add
      path: /spec/sources/2/helm/parameters/-
      value:
        name: vault.injector.enabled
        value: 'true'  
- target:
    group: argoproj.io
    kind: Application
    name: monitoring
    version: v1alpha1
  path: ../../kustomization-common/deployment-serverside-patch.yaml

resources:
  - ../../../src/bundles/10-bootstrapping-utils
  - ../../../src/applications/vault-sidecar-injector/deploy/argocd
  - ../../../src/applications/vault/deploy/argocd  
  - ../../../src/applications/minio/deploy/argocd  
    

