{{- if .Values.httpProxy.create }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: harbor-portal
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  virtualhost:
    fqdn: {{ tpl .Values.httpProxy.fqdn . }}
    tls:
      secretName: {{ tpl .Values.httpProxy.tls.secretName . }}
  routes:
  - services:
    - name: harbor-portal
      port: 80
{{- end }}
