apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow-argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: cicd
  source:
    path: src/applications/argo-cd/workflows
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master
