apiVersion: kustomize.config.k8s.io/v1beta1
# commonLabels:
#   argocd.argoproj.io/instance: seed-job
kind: Kustomization
namespace: argocd

generatorOptions:
 disableNameSuffixHash: true


patches:
  - path: deployment-patch.yaml
    target:
      group: argoproj.io
      kind: Application
      name: .*
      version: v1alpha1


resources:
  - ../../../src/applications/pihole/deploy/argocd
  #- ../../../src/applications/node-red/deploy/argocd
  - ../../../src/applications/mosquitto/deploy/argocd
  - ../../../src/applications/esphome/deploy/argocd
  - ../../../src/applications/home-assistant/deploy/argocd
  - ../../../src/applications/influxdb/deploy/argocd
  # - ../../../src/applications/rest980/deploy/argocd
  - ../../../src/applications/zigbee2mqtt/deploy/argocd
