apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-eventing #camel-k

generatorOptions:
  disableNameSuffixHash: true

resources:
  #- camel-k/timer.yaml
  - camel-k/kn-channel.yaml
  - camel-k/kamelet-beer-source.yaml
  - camel-k/beers.yaml
  #- camel-k/kameletBinding-log.yaml