apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-event-sensor
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - list
      - get
      - watch
