apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-cluster-operator
spec:
  destination:
    name: in-cluster
    namespace: operators
  project: default
  sources:
  - chart: strimzi-kafka-operator
    # https://strimzi.io/docs/operators/latest/deploying#deploying-cluster-operator-helm-chart-str
    repoURL: https://strimzi.io/charts
    targetRevision: 0.48.0
    helm:
      releaseName: strimzi-cluster-operator
      values: |
        watchAnyNamespace: true
