apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow-templates
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  source:
    path: src/applications/argo-workflow-templates/deploy/kustomize
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master