apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  source:
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
      releaseName: cert-manager
      values: |
        extraArgs:
          - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
        ingressShim:
          defaultIssuerName: selfsigned-cluster-issuer
          defaultIssuerKind: ClusterIssuer
          defaultIssuerGroup: cert-manager.io
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
    #path: src/applications/cert-manager/deploy/chart
    #repoURL: https://github.com/nolte/k8s-home-lab.git
    #targetRevision: master
    chart: cert-manager
    repoURL: 'https://charts.jetstack.io'
    # https://artifacthub.io/packages/helm/cert-manager/cert-manager
    targetRevision: v1.12.2
