apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow-rpi-management
spec:
  destination:
    name: in-cluster
    namespace: rpi-homelab-management
  project: default
  source:
    path: src/clusters/rpi-homelab/applications/argo-workflow-management/deploy/kustomize
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: master