apiVersion: v2
dependencies:
  - alias: argoworkflows
    name: argo-workflows
    repository: https://argoproj.github.io/argo-helm
    version: 0.5.1
  - name: argo-workflows-execution
    repository: file://../../../argo-workflow-templates/deploy/chart
    version: 0.0.1
description: Preconfigured argo workflows Deployment
name: argo-workflows
sources:
  - https://github.com/argoproj/argo-helm/tree/master/charts/argo-workflows
type: application
version: 0.2.2