apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  #annotations:
  #  argocd.argoproj.io/sync-wave: "-44"
spec:
  destination:
    name: in-cluster
    namespace: external-secrets
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.19.2
    helm:
      releaseName: external-secrets
      parameters:
        - name: fullnameOverride
          value: "external-secrets"
        # - name: env.VAULT_ADDR
        #   value: "http://vault.vault.svc:8200"
      valuesObject: 
        crds:
          conversion: 
            strategy: None  
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
