apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: ollama
  project: default
  sources:
    - chart: ollama
      repoURL: https://otwld.github.io/ollama-helm/
      targetRevision: 1.53.0
      helm:
        releaseName: ollama
        valuesObject:
          persistentVolume:
            enabled: true
            size: 20Gi
            annotations:
              helm.sh/resource-policy: keep
          ollama:
            models:
              # pull:
              #   -
              run:
                - gemma3:12b
          service:
            type: NodePort
            nodePort: 31434
          extraEnv:
            - name: OLLAMA_NUM_PARALLEL
              value: "1"
            - name: OLLAMA_MAX_LOADED_MODELS
              value: "1"
            - name: OLLAMA_KEEP_ALIVE
              value: "-1"
            - name: OLLAMA_CONTEXT_LENGTH
              value: "4096"
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              #cpu: "12"
              memory: 16Gi
