apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  destination:
    name: in-cluster
    namespace: pihole
  project: default
  source:    
    chart: pihole
    repository: https://mojo2600.github.io/pihole-kubernetes/
    version: 2.5.2
    helm:
      releaseName: pihole
