name: "Lint: Terraform"

on:
  push:
    branches: [ master ]
  pull_request:


jobs:
  lint:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-tf-lint.yaml@v1.1.9
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
