apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio
spec:
  virtualhost:
    fqdn: minio.dev44-just-homestyle.duckdns.org
    tls:
      secretName: cert-manager/wildcard-duckdns-org-tls
  routes:
  - services:
    - name: minio
      port: 80
